ifeq ($(LIBRETRO_COMM_DIR),)
LIBRETRO_COMM_DIR  = $(CORE_DIR)/sys/libretro-common
endif

INCFLAGS   := -I$(LIBRETRO_COMM_DIR)/include

SRC_RENDERER	:=\
	$(CORE_DIR)/renderer/Cinematic.cpp \
	$(CORE_DIR)/renderer/GuiModel.cpp \
	$(CORE_DIR)/renderer/Image_files.cpp \
	$(CORE_DIR)/renderer/Image_init.cpp \
	$(CORE_DIR)/renderer/Image_load.cpp \
	$(CORE_DIR)/renderer/Image_async.cpp \
	$(CORE_DIR)/renderer/aces2_jmh.cpp \
	$(CORE_DIR)/renderer/Image_process.cpp \
	$(CORE_DIR)/renderer/Image_program.cpp \
	$(CORE_DIR)/renderer/Interaction.cpp \
	$(CORE_DIR)/renderer/Material.cpp \
	$(CORE_DIR)/renderer/MegaTexture.cpp \
	$(CORE_DIR)/renderer/Model.cpp \
	$(CORE_DIR)/renderer/ModelDecal.cpp \
	$(CORE_DIR)/renderer/ModelManager.cpp \
	$(CORE_DIR)/renderer/ModelOverlay.cpp \
	$(CORE_DIR)/renderer/Model_beam.cpp \
	$(CORE_DIR)/renderer/Model_ase.cpp \
	$(CORE_DIR)/renderer/Model_liquid.cpp \
	$(CORE_DIR)/renderer/Model_lwo.cpp \
	$(CORE_DIR)/renderer/Model_ma.cpp \
	$(CORE_DIR)/renderer/Model_md3.cpp \
	$(CORE_DIR)/renderer/Model_md5.cpp \
	$(CORE_DIR)/renderer/Model_prt.cpp \
	$(CORE_DIR)/renderer/Model_sprite.cpp \
	$(CORE_DIR)/renderer/RenderEntity.cpp \
	$(CORE_DIR)/renderer/RenderSystem.cpp \
	$(CORE_DIR)/renderer/RenderSystem_init.cpp \
	$(CORE_DIR)/renderer/RenderWorld.cpp \
	$(CORE_DIR)/renderer/RenderWorld_demo.cpp \
	$(CORE_DIR)/renderer/RenderWorld_load.cpp \
	$(CORE_DIR)/renderer/RenderWorld_portals.cpp \
	$(CORE_DIR)/renderer/VertexCache.cpp \
	$(CORE_DIR)/renderer/ParticleLights.cpp \
	$(CORE_DIR)/renderer/draw_common.cpp \
	$(CORE_DIR)/renderer/tr_backend.cpp \
	$(CORE_DIR)/renderer/tr_deform.cpp \
	$(CORE_DIR)/renderer/tr_font.cpp \
	$(CORE_DIR)/renderer/tr_guisurf.cpp \
	$(CORE_DIR)/renderer/tr_light.cpp \
	$(CORE_DIR)/renderer/tr_lightrun.cpp \
	$(CORE_DIR)/renderer/tr_main.cpp \
	$(CORE_DIR)/renderer/tr_orderIndexes.cpp \
	$(CORE_DIR)/renderer/tr_polytope.cpp \
	$(CORE_DIR)/renderer/tr_render.cpp \
	$(CORE_DIR)/renderer/tr_shadowbounds.cpp \
	$(CORE_DIR)/renderer/tr_stencilshadow.cpp \
	$(CORE_DIR)/renderer/tr_subview.cpp \
	$(CORE_DIR)/renderer/tr_trace.cpp \
	$(CORE_DIR)/renderer/tr_trisurf.cpp \
	$(CORE_DIR)/renderer/tr_turboshadow.cpp \

SRC_FRAMEWORK	:=\
	$(CORE_DIR)/framework/CVarSystem.cpp \
	$(CORE_DIR)/framework/CmdSystem.cpp \
	$(CORE_DIR)/framework/Common.cpp \
	$(CORE_DIR)/framework/Compressor.cpp \
	$(CORE_DIR)/framework/Console.cpp \
	$(CORE_DIR)/framework/DemoFile.cpp \
	$(CORE_DIR)/framework/DeclAF.cpp \
	$(CORE_DIR)/framework/DeclEntityDef.cpp \
	$(CORE_DIR)/framework/DeclFX.cpp \
	$(CORE_DIR)/framework/DeclManager.cpp \
	$(CORE_DIR)/framework/DeclParticle.cpp \
	$(CORE_DIR)/framework/DeclPDA.cpp \
	$(CORE_DIR)/framework/DeclSkin.cpp \
	$(CORE_DIR)/framework/DeclTable.cpp \
	$(CORE_DIR)/framework/EditField.cpp \
	$(CORE_DIR)/framework/EventLoop.cpp \
	$(CORE_DIR)/framework/rzip.cpp \
	$(CORE_DIR)/framework/File.cpp \
	$(CORE_DIR)/framework/FileSystem.cpp \
	$(CORE_DIR)/framework/KeyInput.cpp \
	$(CORE_DIR)/framework/UsercmdGen.cpp \
	$(CORE_DIR)/framework/Session_menu.cpp \
	$(CORE_DIR)/framework/Session.cpp \
	$(CORE_DIR)/framework/async/AsyncClient.cpp \
	$(CORE_DIR)/framework/async/AsyncNetwork.cpp \
	$(CORE_DIR)/framework/async/AsyncServer.cpp \
	$(CORE_DIR)/framework/async/MsgChannel.cpp \
	$(CORE_DIR)/framework/async/NetworkSystem.cpp \
	$(CORE_DIR)/framework/async/ServerScan.cpp \

SRC_CM	:=\
	$(CORE_DIR)/cm/CollisionModel_contacts.cpp \
	$(CORE_DIR)/cm/CollisionModel_contents.cpp \
	$(CORE_DIR)/cm/CollisionModel_debug.cpp \
	$(CORE_DIR)/cm/CollisionModel_files.cpp \
	$(CORE_DIR)/cm/CollisionModel_load.cpp \
	$(CORE_DIR)/cm/CollisionModel_rotate.cpp \
	$(CORE_DIR)/cm/CollisionModel_trace.cpp \
	$(CORE_DIR)/cm/CollisionModel_translate.cpp

ifneq ($(GLES),1)
	SRC_DMAP	:=\
		$(CORE_DIR)/tools/compilers/dmap/dmap.cpp \
		$(CORE_DIR)/tools/compilers/dmap/facebsp.cpp \
		$(CORE_DIR)/tools/compilers/dmap/gldraw.cpp \
		$(CORE_DIR)/tools/compilers/dmap/glfile.cpp \
		$(CORE_DIR)/tools/compilers/dmap/leakfile.cpp \
		$(CORE_DIR)/tools/compilers/dmap/map.cpp \
		$(CORE_DIR)/tools/compilers/dmap/optimize.cpp \
		$(CORE_DIR)/tools/compilers/dmap/output.cpp \
		$(CORE_DIR)/tools/compilers/dmap/portals.cpp \
		$(CORE_DIR)/tools/compilers/dmap/shadowopt3.cpp \
		$(CORE_DIR)/tools/compilers/dmap/tritjunction.cpp \
		$(CORE_DIR)/tools/compilers/dmap/tritools.cpp \
		$(CORE_DIR)/tools/compilers/dmap/ubrush.cpp \
		$(CORE_DIR)/tools/compilers/dmap/usurface.cpp
endif

SRC_AAS	:=\
	$(CORE_DIR)/tools/compilers/aas/AASBuild.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASBuild_file.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASBuild_gravity.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASBuild_ledge.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASBuild_merge.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASCluster.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASFile.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASFile_optimize.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASFile_sample.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASReach.cpp \
	$(CORE_DIR)/tools/compilers/aas/AASFileManager.cpp \
	$(CORE_DIR)/tools/compilers/aas/Brush.cpp \
	$(CORE_DIR)/tools/compilers/aas/BrushBSP.cpp

SRC_ROQ	:=\
	$(CORE_DIR)/tools/compilers/roqvq/NSBitmapImageRep.cpp \
	$(CORE_DIR)/tools/compilers/roqvq/codec.cpp \
	$(CORE_DIR)/tools/compilers/roqvq/roq.cpp \
	$(CORE_DIR)/tools/compilers/roqvq/roqParam.cpp

ifneq ($(GLES),1)
SRC_RENDERBUMP	:= \
	$(CORE_DIR)/tools/compilers/renderbump/renderbump.cpp
endif

SRC_SOUND	:=\
	$(CORE_DIR)/sound/snd_cache.cpp \
	$(CORE_DIR)/sound/snd_decoder.cpp \
	$(CORE_DIR)/sound/snd_emitter.cpp \
	$(CORE_DIR)/sound/snd_shader.cpp \
	$(CORE_DIR)/sound/snd_efxfile.cpp \
	$(CORE_DIR)/sound/snd_system.cpp \
	$(CORE_DIR)/sound/snd_wavefile.cpp \
	$(CORE_DIR)/sound/snd_world.cpp

SRC_UI	:=\
	$(CORE_DIR)/ui/BindWindow.cpp \
	$(CORE_DIR)/ui/ChoiceWindow.cpp \
	$(CORE_DIR)/ui/DeviceContext.cpp \
	$(CORE_DIR)/ui/EditWindow.cpp \
	$(CORE_DIR)/ui/FieldWindow.cpp \
	$(CORE_DIR)/ui/GameBearShootWindow.cpp \
	$(CORE_DIR)/ui/GameBustOutWindow.cpp \
	$(CORE_DIR)/ui/GameSSDWindow.cpp \
	$(CORE_DIR)/ui/GuiScript.cpp \
	$(CORE_DIR)/ui/ListGUI.cpp \
	$(CORE_DIR)/ui/ListWindow.cpp \
	$(CORE_DIR)/ui/MarkerWindow.cpp \
	$(CORE_DIR)/ui/RegExp.cpp \
	$(CORE_DIR)/ui/RenderWindow.cpp \
	$(CORE_DIR)/ui/SimpleWindow.cpp \
	$(CORE_DIR)/ui/SliderWindow.cpp \
	$(CORE_DIR)/ui/UserInterface.cpp \
	$(CORE_DIR)/ui/Window.cpp \
	$(CORE_DIR)/ui/Winvar.cpp

SRC_TOOLS	:= \
	$(CORE_DIR)/tools/guied/GEWindowWrapper_stub.cpp

SRC_IDLIB	:=\
	$(CORE_DIR)/idlib/bv/Bounds.cpp \
	$(CORE_DIR)/idlib/bv/Frustum.cpp \
	$(CORE_DIR)/idlib/bv/Sphere.cpp \
	$(CORE_DIR)/idlib/bv/Box.cpp \
	$(CORE_DIR)/idlib/geometry/DrawVert.cpp \
	$(CORE_DIR)/idlib/geometry/Winding2D.cpp \
	$(CORE_DIR)/idlib/geometry/Surface_SweptSpline.cpp \
	$(CORE_DIR)/idlib/geometry/Winding.cpp \
	$(CORE_DIR)/idlib/geometry/Surface.cpp \
	$(CORE_DIR)/idlib/geometry/Surface_Patch.cpp \
	$(CORE_DIR)/idlib/geometry/TraceModel.cpp \
	$(CORE_DIR)/idlib/geometry/JointTransform.cpp \
	$(CORE_DIR)/idlib/hashing/MD4.cpp \
	$(CORE_DIR)/idlib/hashing/MD5.cpp \
	$(CORE_DIR)/idlib/math/Angles.cpp \
	$(CORE_DIR)/idlib/math/Lcp.cpp \
	$(CORE_DIR)/idlib/math/Math.cpp \
	$(CORE_DIR)/idlib/math/Matrix.cpp \
	$(CORE_DIR)/idlib/math/Ode.cpp \
	$(CORE_DIR)/idlib/math/Plane.cpp \
	$(CORE_DIR)/idlib/math/Pluecker.cpp \
	$(CORE_DIR)/idlib/math/Polynomial.cpp \
	$(CORE_DIR)/idlib/math/Quat.cpp \
	$(CORE_DIR)/idlib/math/Rotation.cpp \
	$(CORE_DIR)/idlib/math/Simd.cpp \
	$(CORE_DIR)/idlib/math/Simd_Generic.cpp \
	$(CORE_DIR)/idlib/math/Simd_AltiVec.cpp \
	$(CORE_DIR)/idlib/math/Simd_SSE.cpp \
	$(CORE_DIR)/idlib/math/Simd_SSE2.cpp \
	$(CORE_DIR)/idlib/math/Vector.cpp \
	$(CORE_DIR)/idlib/BitMsg.cpp \
	$(CORE_DIR)/idlib/LangDict.cpp \
	$(CORE_DIR)/idlib/Lexer.cpp \
	$(CORE_DIR)/idlib/Lib.cpp \
	$(CORE_DIR)/idlib/containers/HashIndex.cpp \
	$(CORE_DIR)/idlib/Dict.cpp \
	$(CORE_DIR)/idlib/Str.cpp \
	$(CORE_DIR)/idlib/Parser.cpp \
	$(CORE_DIR)/idlib/MapFile.cpp \
	$(CORE_DIR)/idlib/CmdArgs.cpp \
	$(CORE_DIR)/idlib/Token.cpp \
	$(CORE_DIR)/idlib/Base64.cpp \
	$(CORE_DIR)/idlib/Timer.cpp \
	$(CORE_DIR)/idlib/Heap.cpp


SRC_GLAD	:= \
	$(CORE_DIR)/glad41/glad.c

SRC_SYS	:=\
	$(CORE_DIR)/sys/cpu.cpp \
	$(CORE_DIR)/sys/sys_local.cpp \
	$(CORE_DIR)/sys/threads.cpp \
	$(CORE_DIR)/sys/libretro/retro_events.cpp \
	$(CORE_DIR)/sys/libretro/retro_net.cpp \
	$(CORE_DIR)/sys/libretro/retro_main.cpp \
	$(CORE_DIR)/sys/libretro/libretro.cpp \
	$(CORE_DIR)/sys/libretro/stubs.cpp

SRC_GAME_D3XP	:=\
	$(CORE_DIR)/d3xp/AF.cpp \
	$(CORE_DIR)/d3xp/AFEntity.cpp \
	$(CORE_DIR)/d3xp/Actor.cpp \
	$(CORE_DIR)/d3xp/Camera.cpp \
	$(CORE_DIR)/d3xp/Entity.cpp \
	$(CORE_DIR)/d3xp/BrittleFracture.cpp \
	$(CORE_DIR)/d3xp/Fx.cpp \
	$(CORE_DIR)/d3xp/GameEdit.cpp \
	$(CORE_DIR)/d3xp/Game_local.cpp \
	$(CORE_DIR)/d3xp/Game_network.cpp \
	$(CORE_DIR)/d3xp/Item.cpp \
	$(CORE_DIR)/d3xp/IK.cpp \
	$(CORE_DIR)/d3xp/Light.cpp \
	$(CORE_DIR)/d3xp/Misc.cpp \
	$(CORE_DIR)/d3xp/Mover.cpp \
	$(CORE_DIR)/d3xp/Moveable.cpp \
	$(CORE_DIR)/d3xp/MultiplayerGame.cpp \
	$(CORE_DIR)/d3xp/Player.cpp \
	$(CORE_DIR)/d3xp/PlayerIcon.cpp \
	$(CORE_DIR)/d3xp/PlayerView.cpp \
	$(CORE_DIR)/d3xp/Projectile.cpp \
	$(CORE_DIR)/d3xp/Pvs.cpp \
	$(CORE_DIR)/d3xp/SecurityCamera.cpp \
	$(CORE_DIR)/d3xp/SmokeParticles.cpp \
	$(CORE_DIR)/d3xp/Sound.cpp \
	$(CORE_DIR)/d3xp/Target.cpp \
	$(CORE_DIR)/d3xp/Trigger.cpp \
	$(CORE_DIR)/d3xp/Weapon.cpp \
	$(CORE_DIR)/d3xp/WorldSpawn.cpp \
	$(CORE_DIR)/d3xp/ai/AAS.cpp \
	$(CORE_DIR)/d3xp/ai/AAS_debug.cpp \
	$(CORE_DIR)/d3xp/ai/AAS_pathing.cpp \
	$(CORE_DIR)/d3xp/ai/AAS_routing.cpp \
	$(CORE_DIR)/d3xp/ai/AI.cpp \
	$(CORE_DIR)/d3xp/ai/AI_events.cpp \
	$(CORE_DIR)/d3xp/ai/AI_pathing.cpp \
	$(CORE_DIR)/d3xp/ai/AI_Vagary.cpp \
	$(CORE_DIR)/d3xp/gamesys/DebugGraph.cpp \
	$(CORE_DIR)/d3xp/gamesys/Class.cpp \
	$(CORE_DIR)/d3xp/gamesys/Event.cpp \
	$(CORE_DIR)/d3xp/gamesys/SaveGame.cpp \
	$(CORE_DIR)/d3xp/gamesys/SysCmds.cpp \
	$(CORE_DIR)/d3xp/gamesys/SysCvar.cpp \
	$(CORE_DIR)/d3xp/gamesys/TypeInfo.cpp \
	$(CORE_DIR)/d3xp/anim/Anim.cpp \
	$(CORE_DIR)/d3xp/anim/Anim_Blend.cpp \
	$(CORE_DIR)/d3xp/anim/Anim_Import.cpp \
	$(CORE_DIR)/d3xp/anim/Anim_Testmodel.cpp \
	$(CORE_DIR)/d3xp/script/Script_Compiler.cpp \
	$(CORE_DIR)/d3xp/script/Script_Interpreter.cpp \
	$(CORE_DIR)/d3xp/script/Script_Program.cpp \
	$(CORE_DIR)/d3xp/script/Script_Thread.cpp \
	$(CORE_DIR)/d3xp/physics/Clip.cpp \
	$(CORE_DIR)/d3xp/physics/Force.cpp \
	$(CORE_DIR)/d3xp/physics/Force_Constant.cpp \
	$(CORE_DIR)/d3xp/physics/Force_Drag.cpp \
	$(CORE_DIR)/d3xp/physics/Force_Field.cpp \
	$(CORE_DIR)/d3xp/physics/Force_Spring.cpp \
	$(CORE_DIR)/d3xp/physics/Physics.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_AF.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_Actor.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_Base.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_Monster.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_Parametric.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_Player.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_RigidBody.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_Static.cpp \
	$(CORE_DIR)/d3xp/physics/Physics_StaticMulti.cpp \
	$(CORE_DIR)/d3xp/physics/Push.cpp \
	$(CORE_DIR)/d3xp/Grabber.cpp \
	$(CORE_DIR)/d3xp/physics/Force_Grab.cpp
	
SRC_LIBRETRO := \
	$(LIBRETRO_COMM_DIR)/file/retro_dirent.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_deflate.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_crc32.c \
	$(LIBRETRO_COMM_DIR)/string/stdstring.c \
	$(LIBRETRO_COMM_DIR)/string/rstrtod.c \
	$(LIBRETRO_COMM_DIR)/file/file_path.c \
	$(LIBRETRO_COMM_DIR)/file/file_path_io.c \
	$(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_snprintf.c \
	$(LIBRETRO_COMM_DIR)/features/features_cpu.c \
	$(LIBRETRO_COMM_DIR)/time/rtime.c \
	$(LIBRETRO_COMM_DIR)/streams/file_stream.c \
	$(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c \
	$(LIBRETRO_COMM_DIR)/vfs/vfs_hybrid.c \
	$(LIBRETRO_COMM_DIR)/queues/retro_spsc.c \
	$(LIBRETRO_COMM_DIR)/file/nbio/nbio_intf.c \
	$(LIBRETRO_COMM_DIR)/file/nbio/nbio_stdio.c \
	$(LIBRETRO_COMM_DIR)/file/nbio/nbio_linux.c \
	$(LIBRETRO_COMM_DIR)/file/nbio/nbio_unixmmap.c \
	$(LIBRETRO_COMM_DIR)/file/nbio/nbio_windowsmmap.c \
	$(LIBRETRO_COMM_DIR)/rthreads/rthreads.c \
	$(LIBRETRO_COMM_DIR)/net/net_compat.c \
	$(LIBRETRO_COMM_DIR)/net/net_socket.c \
	$(LIBRETRO_COMM_DIR)/glsym/rglgen.c \
	$(LIBRETRO_COMM_DIR)/formats/image_transfer.c \
	$(LIBRETRO_COMM_DIR)/formats/tga/rtga.c \
	$(LIBRETRO_COMM_DIR)/formats/jpeg/rjpeg.c \
	$(LIBRETRO_COMM_DIR)/formats/dds/rdds.c \
	$(LIBRETRO_COMM_DIR)/formats/audio_transfer.c \
	$(LIBRETRO_COMM_DIR)/formats/wav/rwav.c \
	$(LIBRETRO_COMM_DIR)/formats/vorbis/rvorbis.c \
	$(LIBRETRO_COMM_DIR)/audio/resampler/drivers/sinc_resampler.c \
	$(LIBRETRO_COMM_DIR)/audio/resampler/drivers/sinc_resampler_int16.c \
	$(LIBRETRO_COMM_DIR)/memmap/memalign.c \
	$(LIBRETRO_COMM_DIR)/glsm/glsm.c

# The float sinc resampler has an optional hand-written NEON assembly inner
# loop. It's only used on 32-bit ARM when HAVE_ARM_NEON_ASM_OPTIMIZATIONS is
# defined; the default ARM build uses the C NEON intrinsics path instead, so
# the .S is not part of SOURCES_C. Cores targeting armv7+NEON can add it:
ifeq ($(HAVE_ARM_NEON_ASM_OPTIMIZATIONS),1)
	SOURCES_ASM += $(LIBRETRO_COMM_DIR)/audio/resampler/drivers/sinc_resampler_neon.S
	CFLAGS  += -DHAVE_ARM_NEON_ASM_OPTIMIZATIONS
endif

ifeq ($(GLES),1)
	SRC_RENDERER += \
		$(CORE_DIR)/renderer/glsl/cubeMapShaderFP.o \
		$(CORE_DIR)/renderer/glsl/diffuseMapShaderVP.o \
		$(CORE_DIR)/renderer/glsl/diffuseCubeShaderVP.o \
		$(CORE_DIR)/renderer/glsl/diffuseMapShaderFP.o \
		$(CORE_DIR)/renderer/glsl/fogShaderFP.o \
		$(CORE_DIR)/renderer/glsl/fogShaderVP.o \
		$(CORE_DIR)/renderer/glsl/blendLightShaderVP.o \
		$(CORE_DIR)/renderer/glsl/interactionPhongShaderFP.o \
		$(CORE_DIR)/renderer/glsl/interactionPhongShaderVP.o \
		$(CORE_DIR)/renderer/glsl/interactionShaderFP.o \
		$(CORE_DIR)/renderer/glsl/interactionShaderVP.o \
		$(CORE_DIR)/renderer/glsl/reflectionCubeShaderVP.o \
		$(CORE_DIR)/renderer/glsl/skyboxCubeShaderVP.o \
		$(CORE_DIR)/renderer/glsl/stencilShadowShaderFP.o \
		$(CORE_DIR)/renderer/glsl/stencilShadowShaderVP.o \
		$(CORE_DIR)/renderer/glsl/zfillClipShaderFP.o \
		$(CORE_DIR)/renderer/glsl/zfillClipShaderVP.o \
		$(CORE_DIR)/renderer/glsl/zfillShaderFP.o \
		$(CORE_DIR)/renderer/glsl/zfillShaderVP.o \
		$(CORE_DIR)/renderer/draw_gles2.cpp
	SRC_LIBRETRO += \
		$(LIBRETRO_COMM_DIR)/glsym/glsym_es2.c
else
	SRC_RENDERER += \
		$(CORE_DIR)/renderer/tr_rendertools.cpp \
		$(CORE_DIR)/renderer/draw_arb2.cpp
	SRC_LIBRETRO += \
		$(LIBRETRO_COMM_DIR)/glsym/glsym_gl.c
endif

SOURCES_DIR =
	
DIRS_C  := $(foreach dir,$(SOURCES_DIR), $(wildcard $(dir)/*.c))

# unified core: always the d3xp game module (superset of the base game)
SRC_GAME	:=	$(SRC_GAME_D3XP)

SOURCES_CXX	:=\
	$(SRC_SYS) \
	$(SRC_RENDERER) \
	$(SRC_FRAMEWORK) \
	$(SRC_CM) \
	$(SRC_DMAP) \
	$(SRC_AAS) \
	$(SRC_ROQ) \
	$(SRC_RENDERBUMP) \
	$(SRC_SOUND) \
	$(SRC_UI) \
	$(SRC_TOOLS) \
	$(SRC_IDLIB) \
	$(SRC_GAME) \

SOURCES_C	:=\
	$(LIBRETRO_COMM_DIR)/formats/data_transfer.c \
	$(LIBRETRO_COMM_DIR)/memmap/memmap.c \
	$(SRC_GLAD) \
	$(SRC_LIBRETRO) \
	$(DIRS_C)
